#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = DMRoot

headers       = DMRAffine2D.h DMRCluster.h  DMRGrain.h  DMRImage.h  DMRMicrotrack.h DMRView.h DMRViewHeader.h DMRRun.h  DMRRunHeader.h  DMRLog.h DMRTextFile.h DMRFiducial.h

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
